messages:
  gmc: "&b&lStaff&f&l >> &aModalità Creativa impostata con successo!"
  gms: "&b&lStaff&f&l >> &aModalità Sopravvivenza impostata con successo!"
  gmsp: "&b&lStaff&f&l >> &aModalità Spettatore impostata con successo!"
  flyon: "&b&lStaff&f&l >> &aModalità Volo attivata!"
  flyoff: "&b&lStaff&f&l >> &aModalità Volo disattivata!"
  freeze-playermsg: "&b&lStaff&f&l >> &aSei stato freezzato da un membro dello staff!"
  freeze-staffmsg: "&b&lStaff&f&l >> &aHai freezzato un giocatore!"
  unfreeze-playermsg: "&b&lStaff&f&l >> &cSei stato sbloccato!"
  unfreeze-staffmsg: "&b&lStaff&f&l >> &cHai sbloccato un giocatore!"
  randomtpnull: "&b&lStaff&f&l >> &cNon ci sono giocatori online!"
  staffoff: "&b&lStaff&f&l >> &aStaffMode disabilitata!"
  staffon: "&b&lStaff&f&l >> &aStaffMode abilitata!"
  vanishon: "&b&lStaff&f&l >> &aModalità Vanish abilitata!"
  vanishoff: "&b&lStaff&f&l >> &aModalità Vanish disabilitata!"